ID-26
dltxio/blockchain-id pull request #15
Opened 2021-03-22 01:51 UTC by rellfy

Implements server endpoints for requesting and checking SMS verification codes.

2021-03-22 04:38 UTC, bitcoinbrisbane commented on server/src/getAuthMiddleware.js
> +let middlware = null;
Spelling `middleware`

2021-03-22 04:38 UTC, bitcoinbrisbane commented on server/src/getAuthMiddleware.js
> +  middlware = basicAuth({
Spelling

2021-03-22 04:38 UTC, bitcoinbrisbane commented on server/src/getAuthMiddleware.js
> +  return middlware;
Spelling

2021-03-22 04:38 UTC, bitcoinbrisbane commented on server/src/getAuthMiddleware.js
> +  if (middlware == null)
Spelling

2021-03-22 04:39 UTC, bitcoinbrisbane requested changes
Few small changes

2021-03-22 04:43 UTC, Matt-Tee approved these changes

2021-03-23 01:26 UTC, bitcoinbrisbane approved these changes

2021-03-23 01:27 UTC, merged