ID-52
dltxio/blockchain-id pull request #54
Opened 2021-06-14 20:37 UTC by SharmaDinesh

2021-06-14 22:49 UTC, bitcoinbrisbane commented on app/.env
> +REACT_APP_GPIB_URL="https://testapi.getpaidinbitcoin.com.au"
What is this?

2021-06-14 22:49 UTC, bitcoinbrisbane commented on app/apis/gpib.ts
> +import { REACT_APP_GPIB_URL } from "@env";
We discussed this @SharmaDinesh @ahinchliff

2021-06-14 22:50 UTC, bitcoinbrisbane commented on app/screens/claim/index.tsx
> +  });
What is this?  Why are they hard coded?

2021-06-14 22:51 UTC, bitcoinbrisbane requested changes
It should not be tied to GPIB

2021-06-14 22:57 UTC, bitcoinbrisbane commented
Ok, i can see by the ticket it is a "fake endpoint"

2021-06-14 22:59 UTC, bitcoinbrisbane commented on app/screens/claim/index.tsx
> +  });
Although its a fake endpoint, we should posting real claims data.

2021-06-14 23:41 UTC, rellfy approved these changes

2021-06-15 01:21 UTC, bitcoinbrisbane commented on app/config.dev.json
> +    "endpoint": "https://testapi.getpaidinbitcoin.com.au"
Lets get this from https://github.com/dltxio/idem/blob/master/assets/sites.json#L7 and use key `1x01`

2021-06-15 01:26 UTC, bitcoinbrisbane commented
Post payload should be like https://github.com/dltxio/gpib.admin.api/blob/development/GPIB.Admin.WebAPI/Models/Idem/IdemRequest.cs

Or 

```javascript
const evidence = Joi.object().keys({
      
      
          name: Joi.string().required(),
      
      
          sha256: Joi.string().required()
      
      
        });
      
      
        

      
      
        const bodyValidation: ValidationSchema&lt;server.Claim&gt; = {
      
      
          type: Joi.string().required(),
      
      
          key: Joi.string().required(),
      
      
          value: Joi.string().required(),
      
      
          evidence: Joi.array().items(evidence).min(1)
      
      
        <span class="pl-kos">}</span><span class="pl-kos">;</span>
```

2021-07-26 12:58 UTC, bitcoinbrisbane commented on server/src/config/index.ts
> +    gpib: getEnvVariable("GPIB_API")
This should come form the `sites.json` file, the api value.

2021-07-26 13:00 UTC, bitcoinbrisbane commented on server/src/services/thirdParty/index.ts
> +    let evidences: Array<server.Evidence> = [];
I think these two can be constants

2021-07-26 13:01 UTC, bitcoinbrisbane commented on server/src/endpoint/claims/authorize-thirdParty.ts
> +  if (body.issuer === "gpib") {
This might have to change to a config or something later, but happy with it for the time being

2021-07-26 13:01 UTC, bitcoinbrisbane requested changes
Few suggestions

2021-08-31 02:28 UTC, closed without merging