ID-78
dltxio/blockchain-id pull request #61
Opened 2021-07-28 05:46 UTC by xiangzhe0812

Set PR draft until fix following problem.
1.having truble with auspost api endpoint, send email to aus post support and waiting for response.
2.need logic how we gone handle response from aus post, (store on DB?)

2021-07-28 22:20 UTC, bitcoinbrisbane commented on server-interfaces/src/ausPost.d.ts
> +  type FoundSOurces = {
```suggestion
  type FoundSources = {
```

2021-07-28 22:21 UTC, bitcoinbrisbane requested changes
Few typos

2021-07-29 03:44 UTC, ahinchliff requested changes

2021-07-29 03:44 UTC, ahinchliff commented on server-interfaces/src/ausPost.d.ts
> +declare namespace server {
I dont think you need this here. These interfaces describe how the app should interface with the api. Will the app be sending data to Aus Post directly?

2021-07-29 03:44 UTC, ahinchliff commented on server/src/services/ausPost/aus-post.d.ts
> +    sendVerification: (data: server.Claims) => Promise<server.SuccessResponse>;
Oh i see. This is where you should define the types for AU POST

2021-07-30 05:15 UTC, ahinchliff approved these changes

2021-07-30 06:55 UTC, rellfy approved these changes

2021-07-30 06:56 UTC, merged