ID-8
dltxio/blockchain-id pull request #62
Opened 2021-07-29 03:54 UTC by xiangzhe0812

Get an ETH private and public key pair once user enter mnemonic

How to test 
1. running backend server 
2. using post man to get (http://localhost:3001/api/keypair) and give request body like 
   {
    "mnemonicKey":"tornado **********"
   }
expect get result  like 
{
    "address": "dfgsdfgdfs",
    "privateKey": "sdfgdfgdfg",
    "publicKey": "dfgdfgdfg"
}

2021-07-29 04:11 UTC, bitcoinbrisbane commented
@xiangzhe0812 i think we have our wires crossed ID-8 was supposed to be on the mobile device.  A users keys should only be on their device.

2021-07-30 04:09 UTC, ahinchliff requested changes
Few small changes requested and I have a few questions

2021-07-30 04:09 UTC, ahinchliff commented on app/helpers/setting/EthKeypair.ts
> +  }
this if block is empty

2021-07-30 04:09 UTC, ahinchliff commented on app/navigation/SettingsStackNavigator.tsx
> +      <Stack.Screen
Arent each of these screens exactly the same?

2021-07-30 04:09 UTC, ahinchliff commented on app/screens/setting/index.tsx
> +      case "1x00":
why do the settings need a key? I still havent quite got my head around what the key is for. Is the the key the identiy from DID? @bitcoinbrisbane

2021-07-30 04:09 UTC, ahinchliff commented on app/screens/settings/index.tsx
> +  console.log(settings);
console.log

2021-07-30 04:09 UTC, ahinchliff commented on app/screens/settings/index.tsx
> +    rootStore.Assets.loadSettings();
I dont understand why we are loading the settings? What advantage is there?

2021-07-30 04:26 UTC, bitcoinbrisbane approved these changes
LGTM

2021-07-30 04:54 UTC, rellfy approved these changes

2021-07-30 05:16 UTC, ahinchliff approved these changes

2021-07-30 05:29 UTC, merged