ID-103
dltxio/blockchain-id pull request #82
Opened 2021-11-02 00:58 UTC by NiHS-Bon

https://dltx.atlassian.net/browse/ID-103?atlOrigin=eyJpIjoiY2VmMjk4OTVhNzg5NDk3M2FiYTViNDEzYWZjYmQxMzAiLCJwIjoiaiJ9

2021-11-02 01:00 UTC, drewflaherty approved these changes

2021-11-02 01:10 UTC, bitcoinbrisbane requested changes
2 small changes.

2021-11-02 01:10 UTC, bitcoinbrisbane commented on README.md
> -Meta data is stored in a W3 Verifiable claims JSON object https://www.w3.org/TR/vc-data-model/#contexts:
Id like this line kept

2021-11-02 01:10 UTC, bitcoinbrisbane commented on README.md
> +i)	Update their claims such as Date of Birth, name and address using the verified data on the Idem app.
```suggestion
i)	Update their claims such as date of birth, name and address using the verified data on the Idem app.
```

2021-11-03 03:05 UTC, drewflaherty approved these changes

2021-11-03 03:06 UTC, merged